# Dependency Injection Services Configuration
# Author: Ernedin Zajko <ezajko@root.ba>
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EtfUnsa\SparkDms\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Controllers must be public to be dispatched
  EtfUnsa\SparkDms\Controller\:
    resource: '../Classes/Controller'
    public: true

  EtfUnsa\SparkDms\Controller\Backend\:
    resource: '../Classes/Controller/Backend'
    public: true

  # Console commands
  EtfUnsa\SparkDms\Command\:
    resource: '../Classes/Command'
    tags:
      - { name: 'console.command' }
