# Dependency Injection Services Configuration
# Author: Ernedin Zajko <ezajko@root.ba>
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  RootBa\SparkDms\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Controllers must be public to be dispatched
  RootBa\SparkDms\Controller\:
    resource: '../Classes/Controller'
    public: true

  RootBa\SparkDms\Controller\Backend\:
    resource: '../Classes/Controller/Backend'
    public: true

  # Console commands
  RootBa\SparkDms\Command\:
    resource: '../Classes/Command'
    tags:
      - { name: 'console.command' }
